#!/bin/bash

if["$#""-ne1];then
echo"Usage:$0 filename"
exit 1
fi

FILE=$1
if[!-f"$FILE"];then
echo"file $FILE does not exist."
exit 1
fi

echo"AAAAAAAA">"$FILE"
echo"File contents have been modified to AAAAAAAA."

